version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:rp

  node-app:
    build: .
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
  mongo:
    image: mongo
    environment: 
      -  MONGO_INITDB_ROOT_USERNAME=nikunj 
      -  MONGO_INITDB_ROOT_PASSWORD=mypassword 
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db:


